remote_theme: jekyll-theme-minima-dark
plugins:
  - jekyll-remote-theme
title: Game Of Life in Your Terminal
description: A version of Conway's Game of Life in your terminal written in C
author: Valerio-Cola
show_downloads: true
minima:
  skin: dark