# _config.yml
remote_theme: dracula/gh-pages

# Configurazione del tema
title: Game of Life in Your Terminal
description: A simple implementation of Conway's Game of Life runnable in your Linux terminal using ncurses library
show_downloads: true

# Personalizzazione Dracula
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Personalizzazione colori
colors:
  background: '#282a36'
  foreground: '#f8f8f2'
  selection: '#44475a'
  comment: '#6272a4'
  cyan: '#8be9fd'
  green: '#50fa7b'
  orange: '#ffb86c'
  pink: '#ff79c6'
  purple: '#bd93f9'
  red: '#ff5555'
  yellow: '#f1fa8c'